export type ContactMethod = "email" | "phone_only";

export interface DaycareLocation {
    city: string;
    lat: number;
    lng: number;
}

export interface Daycare {
    id: string;
    name: string;
    isVerified: boolean;
    contactMethod: ContactMethod;
    phone: string;
    email?: string;
    location: DaycareLocation;
    capacity: number;
    nextOpening: string | null;
    priceMonth: number;
}

export const DAYCARES: Daycare[] = [
    // --- VERIFIED DAYCARES (20% = 4 daycares) ---
    {
        id: "d1",
        name: "Little Explorers Coquitlam",
        isVerified: true,
        contactMethod: "email",
        phone: "+1-604-555-0101",
        email: "hello@littleexplorers.ca",
        location: { city: "Coquitlam", lat: 49.2838, lng: -122.7932 },
        capacity: 25,
        nextOpening: "2026-08-01",
        priceMonth: 1200,
    },
    {
        id: "d2",
        name: "Burnaby Montessori Academy",
        isVerified: true,
        contactMethod: "email",
        phone: "+1-604-555-0202",
        email: "admissions@burnabymontessori.ca",
        location: { city: "Burnaby", lat: 49.2488, lng: -122.9805 },
        capacity: 40,
        nextOpening: "2026-09-01",
        priceMonth: 1450,
    },
    {
        id: "d3",
        name: "Port Moody Play & Learn",
        isVerified: true,
        contactMethod: "email",
        phone: "+1-604-555-0303",
        email: "info@pmplaylearn.ca",
        location: { city: "Port Moody", lat: 49.2831, lng: -122.8317 },
        capacity: 15,
        nextOpening: "2026-07-15",
        priceMonth: 1100,
    },
    {
        id: "d4",
        name: "Metrotown Tiny Tots",
        isVerified: true,
        contactMethod: "email",
        phone: "+1-604-555-0404",
        email: "enroll@metrotowntinytots.ca",
        location: { city: "Burnaby", lat: 49.2263, lng: -122.9995 },
        capacity: 35,
        nextOpening: null,
        priceMonth: 1350,
    },

    // --- UNVERIFIED DAYCARES (80% = 16 daycares) ---
    {
        id: "d5",
        name: "Coquitlam Centre Childcare",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-0505",
        location: { city: "Coquitlam", lat: 49.2811, lng: -122.7963 },
        capacity: 20,
        nextOpening: "2026-07-01",
        priceMonth: 1150,
    },
    {
        id: "d6",
        name: "Happy Hearts Burnaby",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-0606",
        location: { city: "Burnaby", lat: 49.2558, lng: -122.9723 },
        capacity: 12,
        nextOpening: null,
        priceMonth: 1300,
    },
    {
        id: "d7",
        name: "Heritage Mountain Daycare",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-0707",
        location: { city: "Port Moody", lat: 49.2991, lng: -122.8441 },
        capacity: 8,
        nextOpening: null,
        priceMonth: 1100,
    },
    {
        id: "d8",
        name: "Brentwood Early Learning",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-0808",
        location: { city: "Burnaby", lat: 49.267, lng: -123.0012 },
        capacity: 30,
        nextOpening: null,
        priceMonth: 1500,
    },
    {
        id: "d9",
        name: "Westwood Plateau Kids",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-0909",
        location: { city: "Coquitlam", lat: 49.305, lng: -122.784 },
        capacity: 10,
        nextOpening: "2026-08-01",
        priceMonth: 1250,
    },
    {
        id: "d10",
        name: "Edmonds Child Care",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1010",
        location: { city: "Burnaby", lat: 49.214, lng: -122.949 },
        capacity: 22,
        nextOpening: null,
        priceMonth: 1200,
    },
    {
        id: "d11",
        name: "Inlet Centre Preschool",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1111",
        location: { city: "Port Moody", lat: 49.2801, lng: -122.822 },
        capacity: 18,
        nextOpening: null,
        priceMonth: 1050,
    },
    {
        id: "d12",
        name: "Pinetree Way Daycare",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1212",
        location: { city: "Coquitlam", lat: 49.288, lng: -122.783 },
        capacity: 16,
        nextOpening: null,
        priceMonth: 1180,
    },
    {
        id: "d13",
        name: "Capitol Hill Playgroup",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1313",
        location: { city: "Burnaby", lat: 49.286, lng: -123.003 },
        capacity: 14,
        nextOpening: null,
        priceMonth: 1350,
    },
    {
        id: "d14",
        name: "Glenayre Early Childhood",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1414",
        location: { city: "Port Moody", lat: 49.278, lng: -122.871 },
        capacity: 25,
        nextOpening: null,
        priceMonth: 1150,
    },
    {
        id: "d15",
        name: "Maillardville French Immersion",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1515",
        location: { city: "Coquitlam", lat: 49.237, lng: -122.863 },
        capacity: 35,
        nextOpening: null,
        priceMonth: 1400,
    },
    {
        id: "d16",
        name: "Central Park Tots",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1616",
        location: { city: "Burnaby", lat: 49.231, lng: -123.018 },
        capacity: 15,
        nextOpening: null,
        priceMonth: 1280,
    },
    {
        id: "d17",
        name: "Newport Village Daycare",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1717",
        location: { city: "Port Moody", lat: 49.283, lng: -122.833 },
        capacity: 12,
        nextOpening: null,
        priceMonth: 1220,
    },
    {
        id: "d18",
        name: "Burquitlam Learning Center",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1818",
        location: { city: "Coquitlam", lat: 49.256, lng: -122.894 },
        capacity: 45,
        nextOpening: null,
        priceMonth: 1190,
    },
    {
        id: "d19",
        name: "Lougheed Town Childcare",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-1919",
        location: { city: "Burnaby", lat: 49.253, lng: -122.891 },
        capacity: 28,
        nextOpening: null,
        priceMonth: 1300,
    },
    {
        id: "d20",
        name: "Austin Heights Kindergarten",
        isVerified: false,
        contactMethod: "phone_only",
        phone: "+1-604-555-2020",
        location: { city: "Coquitlam", lat: 49.251, lng: -122.871 },
        capacity: 20,
        nextOpening: null,
        priceMonth: 1150,
    },
];
